stages:
- name: build
  steps:
  - runScriptConfig:
      image: python:2.7-alpine
      shellScript: |-
        mkdir -p /usr/src/github.com/satomic
        ln -s `pwd` /usr/src/github.com/satomic/pipeline-example-python
        cd /usr/src/github.com/satomic/pipeline-example-python
        ls -l -h -tr
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pipeline-httpserver:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34027
timeout: 60
notification: {}
