stages:
- name: build
  steps:
  - runScriptConfig:
      image: python:2.7-alpine
      shellScript: |-
        mkdir -p /usr/src/github.com/satomic
        ln -s `pwd` /usr/src/github.com/satomic/pipeline-example-python
        cd /usr/src/github.com/satomic/pipeline-example-python
        ls -l -h -tr
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 47.104.65.202/xuefeng/pipeline-httpserver:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 47.104.65.202
    env:
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: catalogs
  steps:
  - runScriptConfig:
      image: satomic/git-box:priv
      shellScript: "echo \"------------- init workspace -------------\"\nmkdir -p
        /usr/src/github.com/satomic\nln -s `pwd` /usr/src/github.com/satomic\ncd /usr/src/github.com/satomic\nls
        -l -h -tr\n\necho \"------------- git clone -------------\"\ngit clone https://github.com/satomic/pipeline-charts.git\nls
        -l -h -tr\n\necho \"------------- cd to app dir -------------\"\ncd /usr/src/github.com/satomic/pipeline-charts/charts/pipeline-httpserver\nls
        -l -h -tr\n\necho \"------------- cp & sed scripts -------------\"\ncp -r
        v0.0.1 v0.0.${CICD_EXECUTION_SEQUENCE}\nsed -i \"s/13/${CICD_EXECUTION_SEQUENCE}/g\"
        ./v0.0.${CICD_EXECUTION_SEQUENCE}/questions.yml\nsed -i \"s/version: 0.0.1/version:
        0.0.${CICD_EXECUTION_SEQUENCE}/g\" ./v0.0.${CICD_EXECUTION_SEQUENCE}/Chart.yaml\n\necho
        \"------------- git config -------------\"\n# init git config\ngit config
        --global user.email \"yxfdental@126.com\"\ngit config --global user.name \"satomic\"\n\necho
        \"------------- git add & commit -------------\"\ngit add *\ngit commit -a
        -m \"version ${CICD_EXECUTION_SEQUENCE}\"\n\necho \"------------- git push
        -------------\"\ncat ~/.gitconfig \ncat ~/.git-credentials\n\ngit push\n\necho
        \"------------- success! -------------\""
timeout: 60
notification: {}
